'use client';

import { useState } from 'react';
import { Wand2, Loader2, AlertCircle, AlignLeft } from 'lucide-react';

export default function SummaryGenerator() {
  const [summary, setSummary] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    setIsLoading(true);
    setError('');
    setSummary('');

    try {
      const response = await fetch('/api/summarize', {
        method: 'POST',
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error);

      setSummary(data.summary);
    } catch (err: any) {
      console.error(err);
      setError(err.message || "Something went wrong generating the summary.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 sm:p-8 transition-all font-sans">
      
      {/* Header Area */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6 gap-4">
        <div>
          <h2 className="text-xl font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <Wand2 className="w-6 h-6 text-indigo-500" />
            2-Minute Revision Sheet
          </h2>
          <p className="text-sm text-slate-500 mt-1">
            Generate a concise, intelligent study guide from your uploaded materials.
          </p>
        </div>
        <button
          onClick={handleGenerate}
          disabled={isLoading}
          className="w-full sm:w-auto bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2.5 px-6 rounded-xl disabled:bg-indigo-300 transition-all shadow-sm flex items-center justify-center gap-2"
        >
          {isLoading ? (
            <>
              <Loader2 className="w-4 h-4 animate-spin" />
              Reading Document...
            </>
          ) : (
            'Generate Summary'
          )}
        </button>
      </div>

      {/* Error Message Display */}
      {error && (
        <div className="mb-6 p-4 bg-red-50 text-red-700 rounded-xl flex items-start gap-3 border border-red-100 animate-in fade-in duration-300">
          <AlertCircle className="w-5 h-5 text-red-500 flex-shrink-0 mt-0.5" />
          <p className="text-sm font-medium">{error}</p>
        </div>
      )}

      {/* Generated Summary Content Container */}
      {summary && (
        <div className="mt-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="bg-slate-50 p-6 sm:p-8 rounded-xl border border-slate-200 shadow-sm relative overflow-hidden">
            {/* Subtle decorative edge */}
            <div className="absolute top-0 left-0 w-1 h-full bg-indigo-400"></div>
            
            <div className="flex items-center gap-2 mb-5 pb-4 border-b border-slate-200">
              <AlignLeft className="w-5 h-5 text-indigo-600" />
              <h3 className="font-bold text-slate-900 tracking-tight">Executive Summary</h3>
            </div>
            
            {/* Tailwind typography plugin (prose) handles the markdown tags generated by Gemini smoothly.
              We enforce text-slate-700 for high readability contrast.
            */}
            <div className="text-slate-700 whitespace-pre-wrap leading-relaxed prose prose-slate max-w-none prose-headings:text-slate-900 prose-headings:font-bold prose-strong:text-indigo-900">
              {summary}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}